import Head from "next/head";
import { PageData } from "@/types/data";
import { getHomePageData } from "@/service/homepage";
import HomePage from "@/components/HomePage";

export const getStaticProps = async () => {
  const homes = await getHomePageData();
  return {
    props: { homes }
  };
};

export default function Home({ homes }: PageData.IndexPageData) {
  return (
    <>
      <Head>
        <title>Space Tourism</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container m-auto p-6">
        <HomePage homes={homes}/>
      </main>
    </>
  );
}
